### PR TITLE
Kaoru freds device id apis

### PR DESCRIPTION
**Pull request by KaoruDev**
Hi @fredsadaghiani @mwylde 

**Disclosure**: I'm currently interviewing at Sift Science, which prompted me to look into this gem.

I noticed a few things that might help yall out in the future:

- @mwylde suggested scoping errors thrown by this `gem`. I went ahead and created a small hierarchy.

`Sift::Error` is the top level error `class`, inheriting from `StandardError`. Both `Sift::HttpRequestError` and `Sift::ConfigError` inherit from `Sift::Error`. This can be found in `lib/sift/error.rb` This way a client can `rescue` from just `Sift::Error` and not have to worry if they are swallowing errors pointing to **standard errors**.

- I rebased the branch for you.

- I noticed in `resource.rb` `http_request` was taking in a `block` and converting it into a `proc`. This is probably a preoptimization but it's best to use `yield` instead of `&blk`. [Reference](https://github.com/JuanitoFatas/fast-ruby#proccall-and-block-arguments-vs-yieldcode). Although it seemed more `rubyish` to pass the response to the `private` method and have it handle the error case.

- Deleted `lib/sift/credentials.rb` since it wasn't doing anything. I moved the `attr_accessor` settings to the main module in `lib/sift.rb`

- RSpec `expects` accepts blocks, so you don't need to create `lambdas` before hand. That'll just clean up the code a little bit.

Would love to hear your thoughts and hopefully we'll get to meet!

### CODE REVIEW

**Comment by KaoruDev** [comment]
hrmm specs run green locally on `2.3.0` but it seems `addressable` requires ruby versions `>= 1.9.0`. Here's the commit that drops `1.8` support: https://github.com/sporkmonger/addressable/commit/78221c846810b5f8b35096939a9c0a4afbac4433

Not sure if yall want to also drop `1.8` support. Otherwise you'd have to lock the gem to `v2.3.8`

**Comment by fredsadaghiani** [comment]
@KaoruDev Thanks for the PR! @mwylde can you take a look and review?

**Comment by fredsadaghiani** [comment]
@KaoruDev The build on this isn't passing. Can you take a look and make the build green please.

**Comment by fredsadaghiani** [comment]
To be clear, I think dropping 1.8 support is fine if that's what it takes to get it green.

**Comment by KaoruDev** [comment]
@fredsadaghiani if we drop `1.8` support I'd recommend bumping the gem version as well.

Let me play around with this i might be able to refactor the gem so we _don't_ have to drop `1.8` support.

**Comment by fredsadaghiani** [comment]
SGTM

On Fri, Apr 29, 2016 at 2:10 PM, Kaoru Kohashigawa <notifications@github.com

**Pull request closed without merging**
